spring.application.name=basketservice
server.port=0

eureka.client.fetch-registry=true
eureka.client.register-with-eureka = true
eureka.client.service-url.defaultZone= http://localhost:8090/eureka
# Eurekaya kayıt olurken hostname yerine Ip adresini kullanır
eureka.instance.prefer-ip-address= true
eureka.instance.instance-id= ${spring.application.name}:${instanceId:${random.value}}

spring.data.redis.host = localhost
spring.data.redis.port = 6379

jwt.secret.key=0WWR7nH/+GUTcfTrNpFvRdWXWIuud70ocHxplDprmlU=
jwt.expiration=9000000