spring.application.name=salesservice
server.port=0

eureka.client.fetch-registry=true
eureka.client.register-with-eureka = true
eureka.client.service-url.defaultZone= http://localhost:8090/eureka
# Eurekaya kayıt olurken hostname yerine Ip adresini kullanır
eureka.instance.prefer-ip-address= true
eureka.instance.instance-id= ${spring.application.name}:${instanceId:${random.value}}

spring.data.mongodb.database=salesservicedb
spring.data.mongodb.port = 27017
spring.data.mongodb.uri = mongodb://localhost:27017

jwt.secret.key=0WWR7nH/+GUTcfTrNpFvRdWXWIuud70ocHxplDprmlU=
jwt.expiration=9000000

spring.cloud.stream.kafka.binder.brokers=localhost:29092
# "clearBasket-out-0" (StreamBridge'de kullanılan) -> "clear-basket-topic" topic'ine yönlendirilir.
spring.cloud.stream.bindings.clearBasket-out-0.destination=clear-basket-event
